# Workflow to run tests
name: test-suite

# When will this workflow run?
on:
  # run on every push to main, i.e. PR merges
  push:
    branches: [ "main" ]

  # Triggers the workflow on pushes to open pull requests with code changes
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/test_suite.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# No permissions required to run this code
permissions: {}

jobs:
  test-suite:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
    - name: Checkout code
      with:
        persist-credentials: false
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
  
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv mlstep_venv
        . mlstep_venv/bin/activate
        pip install .[dev]

    - name: Run tests
      if: always()
      run: |
        cd ${{ github.workspace }}
        . mlstep_venv/bin/activate
        pytest -v test/
